image: "luckycometdaft/emcigccarm:v3"

stages: # List of stages for jobs and their order of execution
    - build
    - test
    - deploy
    
build-job: # This job runs the build stage first
    stage: build
    script:
        - echo "Compiling the code..."
        - echo "Compile complete."
        - arm-none-eabi-gcc -v
        - make
        - mkdir testOutput
        - cd testOutput
        - renode-test /home/renode/tests/platforms/STM32F103.robot
    artifacts:
        when: always
        paths:
            - testOutput

        
robot-run-job: # This job runs in the test stage.
    stage: test # Runs if build stage completes successfully.
    script:
        - cd Ex02-CopyString
        - make
        - renode-test ASM-CopyString.robot
    artifacts:
        when: always
        paths:
            - Ex02-CopyString/report.html
            - Ex02-CopyString/log.html